name: MoeSign
main: cn.whiteg.moesign.MoeSign
version: 1.1
api-version: 1.13
author: MoeWhite
depend: [MMOCore, Vault]
softdepend: [MoeEco, MoeAfk]
commands:
  moesign:
    description: The is MoeSign Command
    aliases: ['ms']
  sign:
    description: The is Sign Command
    aliases: ['sn']